# Numpy is the fundamental package for scientific computing in python . it is library that provide multi dimenesional array object and many object . Or if we want any mathematical computation then we will use this library

In [28]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [29]:
import numpy as np

In [30]:
array = np.array([1,3,2,5,4])

In [31]:
array.sort()

In [32]:
array

array([1, 2, 3, 4, 5])

In [33]:
twodarray  = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
twodarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# dtype parameter --> which can help us out the decide about the size of the data tpye of the array that which we are going to store in our array
np.array([1,2,3], dtype=np.int32) # np.int64 , np.float32 , np.float64 , np.bool

array([1, 2, 3], dtype=int32)

In [45]:
# range() from i in range (15): this fill the element in the list
# if we want to fill directly element in the array then we can use arange() function of numpy
data = np.arange(16)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
# if we have to convert the shape of our array then we use reshape() fn to do it
data.reshape(4,4) # it convert my array shape to as per our needs

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
# ones() fn --> it make the grid of 1's as per our needs
np.ones((3,3)) # it make the grid of 1's as per our

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# zero() fn --> it make the grid of 0's as per our needs
np.zeros((3,3)) # it make the grid of 0's as per our

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# random() function --> it fill the random value between the range of 0 and 1
np.random.random((3,3))

array([[0.8622343 , 0.22069802, 0.2748277 ],
       [0.38544705, 0.82536206, 0.11628601],
       [0.65365206, 0.18734983, 0.5515241 ]])

In [43]:
# linspace() function --> it fill the value between the range of 0 and 1 but it is equally spaced value
np.linspace(0,1,5) # it fill the value between the range of 0 and 1 but it is equally spaced value

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
# Identity() --> it create the matrix as identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Attributes

In [ ]:
# ndim -> n dimensional array , np.array([1,2,3]).ndim
# shape -> it give the shape of the array (rows , cols) , np.array([1,2,3]).shape --> 1,3
# size -> it give the total number of element in the array , np.array([1,2,3]).size --> 3
# itemsize -> it give the size of each element in the array , np.array([1,2,3]).itemsize --> 4 bytes
# dtype -> it give the data type of the array , np.array([1,2,3]).dtype --> int32 

In [46]:
# astype() fn --> this fn help to figure to the data type of the column in the dataset in pandas and will
# use in numpy as well for getting the date type chnage over the array 

array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
array.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [48]:
array.dtype

dtype('int64')

In [49]:
array = array.astype('float64')

In [50]:
array.dtype

dtype('float64')

# MAthematical operation in numpy

In [54]:
# scalar operation --> a scalar value would be multiplied throughtout the array.
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
# we can also use realtional operation on the array as well
arr>6

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [60]:
# vector operations --> operation will be in btw the given number of metric 
arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(17,33).reshape(4,4)

In [62]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [64]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
# Important fn in numpy 

# max() -- give me the max value of the matrix , np.max(arr1)
# axis() -- it give the idea about the any operation inside the specific row or colm or we can get a specifc value rowiseor colwise
# axis ==0 columnwise , axis == 1 rowise
# sum() --> calculate the sum of the all value in the matrix
# prod() --> claculate the product of all the value in the matrix  

# Statistical function 


In [ ]:
# mean() --> to calculate the mean of the array , np.mean()
np.mean(arr1)

# for calculate mean of every row
np.mean(arr1 , axis=1)
# for every coulm wise
np.mean(arr1 , axis=0)

array([4., 5., 6.])

In [69]:
np.mean(arr1 , axis=0)

array([ 7.,  8.,  9., 10.])

In [ ]:
# standard deviation --> to calculate std of all value or array
np.std(arr1) # go row wise , colwise

np.float64(4.6097722286464435)

In [ ]:
# median --> to calculate the median of all the value of array or matrix
np.median(arr1)# go row wise , colwise

np.float64(8.5)

In [73]:
# variance of all value inside the array or matrix
np.var(arr1)

np.float64(21.25)

In [74]:
# Dot Product of Metrices

np.dot(arr1 , arr2)

array([[ 250,  260,  270,  280],
       [ 618,  644,  670,  696],
       [ 986, 1028, 1070, 1112],
       [1354, 1412, 1470, 1528]])

In [75]:
# log() --> to calculate the log of each value
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

In [ ]:
# round() --> to round of the floar valueto nearest integer
# ceil() --> to get upper one value
# floor --> to get the vlaue lower one 

In [ ]:
# transpose of the matrix . row (3,4) can convert to (4,3)
np.transpose(arr1) # transpose(arr) or arr.T
arr2.T

array([[17, 21, 25, 29],
       [18, 22, 26, 30],
       [19, 23, 27, 31],
       [20, 24, 28, 32]])

In [79]:
# ravel() --> convert 2d or 3d array into 1d array , any n dimension array can convert to one d array
np.ravel(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
# Indexing --> lists[,size-1] -- to have access over the value 
# 3d axis [z-axis , x-axis , y-axis]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [83]:
# slicing -- similar approach just like the list [:]
# 2d -  [row1: row2, col1:col2] 
arr1[0,:]
arr1[:,2]

array([ 3,  7, 11, 15])

In [ ]:
# nditer() --> this works to iterate on 2d or 3d array of getiing each value

# Stacking --> we are joing the array together , size of the array must be the same
# horizontal , row by row done , hstack()
# vertical , colo by col joining is donw , vstack()

# np.hstack((arr1 , arr2))
# np.vstack((arr1 , arr2))

# Splitting , 
# Horizontal -- np.hsplit(arr , no of parts in whcih array has to be split)
# vertical -- np.vsplit(arr , no of parts in whcih array has to be split)